version: '3.1'

services:
  mysql:
    image: mysql:8.0.26
    container_name: KelseyMysql
    restart: always
    ports:
      - "3306:3306"
    environment:
        #数据库密码
      - MYSQL_ROOT_PASSWORD=123456
        #创建的库
      - MYSQL_DATABASE=tasty
        #允许多IP连接数据库
      - MYSQL_ROOT_HOST=%

  redis:
    image: redis:latest
    container_name: KelseyRedis
    ports:
      - "6379:6379"
    restart: always

  tastyWeb:
    image: tasty
    container_name: tasty1
    ports:
      - "8082:8082"
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=tasty
      - DATABASE_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
