server:
  port: 8082


spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tasty
      username: root
      password: '030530'
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1

# mybatis-plus??
mybatis-plus:
  # ????MyBatis????
  check-config-location: false
  # MyBatis??????
  config-location:
  # MyBaits???????
  type-aliases-package: com.cs183.tasty.entity
  # Mapper????XML???? ???classpath*:/mapper/**/*.xml?
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # TypeHandler????
  type-handlers-package:
  configuration:
    # ????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # ????????????
    map-underscore-to-camel-case: true
    # ??Mybatis????????true
    cache-enabled: true
  global-config:
    # ???mybatis-plus?logo
    banner: true
    db-config:
      # ????????
      id-type: auto
      # ??????
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0




